### ISSUE TITLE
Parowanie - bug

### ISSUE THREAD

**Issue by blashkow** [silent-rock/nwn_BS#102]
Ponoć ten skill zbugowany:

https://forums.beamdog.com/discussion/68599/what-to-do-with-parry

**Comment by silent-rock** [comment]
@blashkow parowanie było zbugowane od samego początku gry. Dopóki breamdog tego nie poprawi to raczej nic z tym nie zrobimy.
Ja miałem pomysł taki, żeby parowanie zmienić na fortyfikację i premia tej umiejętności mogłaby dawać redukcję obrażeń fizycznych przy trafieniach krytycznych, ale nie potrafię tego oskryptować i nie mam pewności czy to jest w ogóle możliwe, nawet z nwnx. Na Arelith albo na The Awakening mieli taką zmianę, ale u nich to działało na lua, gdzie mieli przepisany cały silnik walki.
