### ISSUE TITLE
Skrypt/system 

### ISSUE THREAD

**Issue by iacobmod** [silent-rock/nwn_BS#12]
Potrzebny drobny systemik, myślę nie trudny do zrobienia. Skok do lokacji odpalany z konwersacji, gdzie destynacje podawałoby się w zmiennych. I co ważne by tych destynacji mogło być kilka z jednej konwersacji.
Służył będzie do podróży statkiem, karawaną itp. Może równie dobrze być wygrzebany gdzieś z vaulta - ja osobiście nie znalazłem.

**Comment by iacobmod** [comment]
O tym sposobie wiem. Dla kazdej lokalizacji musi byc osobny skrypt. Myslalem by zalatwic to 1 skryptem a lokalizacje czerpane bylyby przez niego ze zmiennych. Tym sposobem, gdy dochodzi nam jakas lokalizacja nie musimy robic kolejnego skryptu.

**Comment by silent-rock** [comment]
@iacobmod zamykam to, nie udało mi się wynaleźć nic, co by odpowiadało opisowi :( Teoretycznie można rozpisać w jednym skrypcie, ale nie mam pojęcia jak ogarnąć to ograniczenie, że na konwersacji jest 'action taken' i tam się odwołuje do osobnego skryptu. Jak patrzyłem po jakichś przykładowych modułach to wszędzie to były faktycznie osobne skrypty do obsługi każdej akcji wykonywanej z konwersacji.
Może zz dialog jakoś to ogarnia? https://neverwintervault.org/project/nwn1/script/zz-dialog-166
