### ISSUE TITLE
Lokacja startowa/powitalna

### ISSUE THREAD

**Issue by silent-rock** [silent-rock/nwn_BS#17]
Fajnie by było, jakby w module znalazła się lokacja startowa/powitalna, do której najpierw trafia gracz:
* wyłączone pvp
* jakiś komunikat powitalny
* podstawowe informacje o serwerze: regulamin, zarys fabularny, info o stronie/forum, zmiany, aktualizacje
* portal przenoszący gracza do kolejnej lokacji - być może w konwersacji odpalanej na portalu fajnie by było dać graczowi wybór do jakiej lokacji chciałby trafić (ewentualnie wybór ograniczyć przez przynależność gracza do gildii/frakcji lub jego poziom postaci)

**Comment by blashkow** [comment]
Jest. Nie ma tablic z regulaminem i linkiem do www. Zarys fabularny zostawimy na stronie www.
Przejście jest drzwiami do arkońskiego portalu.
