### ISSUE TITLE
Niszczycielskie trafienie krytyczne

### ISSUE THREAD

**Issue by silent-rock** [silent-rock/nwn_BS#39]
Jeśli nie uda się jakoś ogarnąć działania NTK skryptami (zgodnie z opisem w wiki; chyba tylko z nwnx jest to możliwe), trzeba będzie wyłączyć możliwość wybrania atutu przez graczy. To chyba najważniejsza rzecz pod kątem balansu.

**Comment by blashkow** [comment]
Wysoki priorytet i wg nie najłatwiejsze rozwiązanie to deaktywacja atutu.

**Comment by silent-rock** [comment]
Tymczasowo wyłączone.
