### ISSUE TITLE
Jak znaleźć w aurorze lokację dla danego npc?

### ISSUE THREAD

**Issue by blashkow** [silent-rock/nwn_BS#5]
Sprawdzam z palety: mamy masę npc, których nie  mam w rozpisce w docsie - chciałbym sprawdzić gdzie oni zostali umieszczeni . Jak to zrobić w aurorze?

**Comment by iacobmod** [comment]
Własciwie nie jest mozliwe. Możemy we właściwosciach npca umieszczac inf w "uwagach" skad pochodzi.

**Comment by iacobmod** [comment]
Większość npców z dziwnymi imionami i z resrefem zaczynającym się na kucz_ to npce kuczai ze Starej Wsi i ew. Rozdroży w Gradowej Kniei. Również gnomy i krasnoludy z Perudy.
Reszta to zrobione przeze mnie i tu pewnie będą raczej w Arkonie, okolicach, ale też w Szczerbcu, na Rozdrozach Głównego Traktu ....
