### ISSUE TITLE
Zmiany w statystykach zbroi

### ISSUE THREAD

**Issue by silent-rock** [silent-rock/nwn_BS#55]
Do zmiany armor.2da - testowo. Obadać czy to da jakieś realne efekty.

Przeszywanica 1/8
2/6 - na 2/7
3/4 - na 3/6
4/4 - na 4/5
5/2 - na 5/4
6/1 - na 6/3
7/1 - na 7/2
Płytowa 8/1

**Comment by blashkow** [comment]
w tym modzie KK powinno to być rdy.

**Comment by silent-rock** [comment]
Jest w KK, ale do tego moda nie mamy haków. To prosta zmiana w jednym pliku 2da, tylko muszę sobie przeliczyć jakie to konsekwencje będzie za sobą niosło i ewentualnie później podmienić tych kilka wartości w 2da i ogarnąć poprawę wszystkich opisów w tlk.
