### ISSUE TITLE
Boost dla gracza przy używaniu lekkiej i ciężkiej kuszy

### ISSUE THREAD

**Issue by silent-rock** [silent-rock/nwn_BS#64]
Na onPlayerEquip i onPlayerUnequip trzeba dorzucić funkcję, która doda postaci dodatkowy atak z max premią do AB.

EDIT: chyba faktycznie lepiej by to było zrobić boostem do dmg. Może jako item property na on equip, który dorzuci większy dmg, rekompensujący mniejszą liczbę ataków na rundę (trzeba tylko sprawdzić czy to nie zwiększa wartości itemu).

**Comment by blashkow** [comment]
Zastanawiam się czy nie dać lekkiego boosta w dmg kuszom. W końcu "kusznik" miałby sens.

**Comment by silent-rock** [comment]
@blashkow ten dodatkowy atak powinien pomóc. W baseitems.2da chyba jeszcze zmieniałem dmg bazowy. Generalnie na itemach przydałoby się pograć trochę tymi obrażeniami, żeby wyrównać jeszcze mocniej balans broni. Na pewno bronie 2h powinny mieć większy dmg dodatkowy, jakbyśmy wdrażali bronie z socketami lub z jakimiś ulepszeniami to też powinny mieć o 1 więcej socket niż bronie 1h.
